/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as AoVivoRouteImport } from './routes/ao-vivo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseTypeRouteImport } from './routes/browse.$type'
import { Route as TitleTypeSlugRouteImport } from './routes/title.$type.$slug'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AoVivoRoute = AoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseTypeRoute = BrowseTypeRouteImport.update({
  id: '/browse/$type',
  path: '/browse/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleTypeSlugRoute = TitleTypeSlugRouteImport.update({
  id: '/title/$type/$slug',
  path: '/title/$type/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/search': typeof SearchRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/title/$type/$slug': typeof TitleTypeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/search': typeof SearchRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/title/$type/$slug': typeof TitleTypeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ao-vivo': typeof AoVivoRoute
  '/search': typeof SearchRoute
  '/browse/$type': typeof BrowseTypeRoute
  '/title/$type/$slug': typeof TitleTypeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ao-vivo'
    | '/search'
    | '/browse/$type'
    | '/title/$type/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ao-vivo' | '/search' | '/browse/$type' | '/title/$type/$slug'
  id:
    | '__root__'
    | '/'
    | '/ao-vivo'
    | '/search'
    | '/browse/$type'
    | '/title/$type/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AoVivoRoute: typeof AoVivoRoute
  SearchRoute: typeof SearchRoute
  BrowseTypeRoute: typeof BrowseTypeRoute
  TitleTypeSlugRoute: typeof TitleTypeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao-vivo': {
      id: '/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AoVivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$type': {
      id: '/browse/$type'
      path: '/browse/$type'
      fullPath: '/browse/$type'
      preLoaderRoute: typeof BrowseTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$type/$slug': {
      id: '/title/$type/$slug'
      path: '/title/$type/$slug'
      fullPath: '/title/$type/$slug'
      preLoaderRoute: typeof TitleTypeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AoVivoRoute: AoVivoRoute,
  SearchRoute: SearchRoute,
  BrowseTypeRoute: BrowseTypeRoute,
  TitleTypeSlugRoute: TitleTypeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
